ALTER TABLE products
    ADD COLUMN description VARCHAR(70);

INSERT INTO products (name, short_name, category, stock_quantity, price, reserved_qty, description) VALUES
    ('Acetaminofen 500 mg', 'Acetaminofen', 'MEDICINES', 120, 2.50, 0, 'Alivia dolor y fiebre en adultos'),
    ('Ibuprofeno 400 mg', 'Ibuprofeno', 'MEDICINES', 90, 3.20, 0, 'Antiinflamatorio para dolor muscular'),
    ('Amoxicilina 500 mg', 'Amoxicilina', 'MEDICINES', 60, 6.80, 0, 'Antibiotico de amplio espectro'),
    ('Loratadina 10 mg', 'Loratadina', 'MEDICINES', 80, 4.10, 0, 'Antihistaminico para alergia'),
    ('Omeprazol 20 mg', 'Omeprazol', 'MEDICINES', 100, 5.40, 0, 'Reduce la acidez estomacal'),
    ('Losartan 50 mg', 'Losartan', 'MEDICINES', 70, 7.90, 0, 'Controla la presion arterial'),
    ('Metformina 850 mg', 'Metformina', 'MEDICINES', 85, 4.60, 0, 'Ayuda a controlar la glucosa'),
    ('Atorvastatina 20 mg', 'Atorvastatina', 'MEDICINES', 55, 9.30, 0, 'Reduce el colesterol en sangre'),
    ('Azitromicina 500 mg', 'Azitromicina', 'MEDICINES', 40, 12.50, 0, 'Antibiotico de corta duracion'),
    ('Diclofenac sodico 50 mg', 'Diclofenac', 'MEDICINES', 75, 3.80, 0, 'Alivia dolor e inflamacion'),
    ('Salbutamol inhalador', 'Salbutamol', 'MEDICINES', 35, 14.20, 0, 'Abre las vias respiratorias'),
    ('Prednisona 5 mg', 'Prednisona', 'MEDICINES', 50, 4.90, 0, 'Corticoide de uso oral'),
    ('Cetirizina 10 mg', 'Cetirizina', 'MEDICINES', 95, 3.60, 0, 'Alivia estornudos y picazon'),
    ('Clonazepam 2 mg', 'Clonazepam', 'MEDICINES', 25, 8.70, 0, 'Ansiolitico de uso controlado'),
    ('Enalapril 10 mg', 'Enalapril', 'MEDICINES', 65, 5.10, 0, 'Tratamiento de hipertension'),
    ('Amlodipino 5 mg', 'Amlodipino', 'MEDICINES', 70, 4.40, 0, 'Relaja los vasos sanguineos'),
    ('Levotiroxina 50 mcg', 'Levotiroxina', 'MEDICINES', 45, 6.20, 0, 'Reemplazo de hormona tiroidea'),
    ('Metoclopramida 10 mg', 'Metoclopramida', 'MEDICINES', 55, 3.10, 0, 'Alivia nauseas y vomito'),
    ('Ranitidina 150 mg', 'Ranitidina', 'MEDICINES', 60, 4.00, 0, 'Disminuye el acido gastrico'),
    ('Ciprofloxacina 500 mg', 'Ciprofloxacino', 'MEDICINES', 40, 8.40, 0, 'Antibiotico para infecciones'),
    ('Dexametasona 4 mg', 'Dexametasona', 'MEDICINES', 30, 5.80, 0, 'Corticoide antiinflamatorio'),
    ('Clorfeniramina 4 mg', 'Clorfeniramina', 'MEDICINES', 110, 2.20, 0, 'Alivia sintomas de resfriado'),
    ('Naproxeno 250 mg', 'Naproxeno', 'MEDICINES', 80, 3.90, 0, 'Analgesico de accion prolongada'),
    ('Tramadol 50 mg', 'Tramadol', 'MEDICINES', 20, 11.60, 0, 'Analgesico para dolor moderado'),
    ('Insulina NPH', 'Insulina NPH', 'MEDICINES', 15, 28.90, 0, 'Controla la glucosa en diabetes'),
    ('Suero oral sobre', 'Suero oral', 'MEDICINES', 150, 1.80, 0, 'Repone liquidos y electrolitos'),
    ('Jarabe para la tos', 'Jarabe tos', 'MEDICINES', 70, 6.50, 0, 'Calma la tos y la irritacion'),
    ('Vitamina C 1 g', 'Vitamina C', 'MEDICINES', 130, 4.70, 0, 'Refuerza las defensas del cuerpo'),
    ('Complejo B tabletas', 'Complejo B', 'MEDICINES', 90, 5.30, 0, 'Apoya energia y sistema nervioso'),
    ('Acido folico 5 mg', 'Acido folico', 'MEDICINES', 60, 3.40, 0, 'Suplemento para el embarazo'),
    ('Calcio 600 mg', 'Calcio', 'MEDICINES', 75, 6.10, 0, 'Fortalece huesos y dientes'),
    ('Sulfato ferroso 300 mg', 'Sulfato ferroso', 'MEDICINES', 50, 4.20, 0, 'Trata la deficiencia de hierro'),
    ('Paracetamol infantil gotas', 'Paracetamol inf', 'MEDICINES', 85, 5.90, 0, 'Baja la fiebre en ninos'),
    ('Ibuprofeno suspension', 'Ibuprofeno susp', 'MEDICINES', 65, 6.40, 0, 'Alivia dolor infantil'),
    ('Amoxicilina suspension', 'Amoxi susp', 'MEDICINES', 55, 7.80, 0, 'Antibiotico pediatrico'),
    ('Clotrimazol crema 1%', 'Clotrimazol', 'MEDICINES', 40, 5.50, 0, 'Trata hongos en la piel'),
    ('Miconazol ovulos', 'Miconazol', 'MEDICINES', 35, 7.20, 0, 'Antimicotico de uso vaginal'),
    ('Nistatina suspension', 'Nistatina', 'MEDICINES', 30, 8.10, 0, 'Trata candidiasis oral'),
    ('Hidrocortisona crema 1%', 'Hidrocortisona', 'MEDICINES', 45, 4.80, 0, 'Calma irritacion de la piel'),
    ('Betametasona crema', 'Betametasona', 'MEDICINES', 25, 6.90, 0, 'Crema para inflamacion cutanea'),
    ('Fluconazol 150 mg', 'Fluconazol', 'MEDICINES', 40, 9.40, 0, 'Antimicotico de dosis unica'),
    ('Albendazol 400 mg', 'Albendazol', 'MEDICINES', 50, 3.70, 0, 'Tratamiento contra parasitos'),
    ('Metronidazol 500 mg', 'Metronidazol', 'MEDICINES', 60, 4.30, 0, 'Antibiotico para infecciones'),
    ('Doxiciclina 100 mg', 'Doxiciclina', 'MEDICINES', 35, 7.60, 0, 'Antibiotico de amplio uso'),
    ('Captopril 25 mg', 'Captopril', 'MEDICINES', 55, 3.50, 0, 'Antihipertensivo de accion rapida'),
    ('Furosemida 40 mg', 'Furosemida', 'MEDICINES', 45, 2.90, 0, 'Diuretico para retencion de liquido'),
    ('Espironolactona 25 mg', 'Espironolactona', 'MEDICINES', 30, 5.20, 0, 'Diuretico que ahorra potasio'),
    ('Warfarina 5 mg', 'Warfarina', 'MEDICINES', 20, 6.70, 0, 'Anticoagulante de uso oral'),
    ('Aspirina 100 mg', 'Aspirina', 'MEDICINES', 140, 2.10, 0, 'Protege la salud cardiovascular'),
    ('Simvastatina 20 mg', 'Simvastatina', 'MEDICINES', 40, 8.20, 0, 'Ayuda a bajar el colesterol'),
    ('Claritromicina 500 mg', 'Claritromicina', 'MEDICINES', 30, 13.40, 0, 'Antibiotico para vias respiratorias'),
    ('Jabon antibacterial', 'Jabon antibac', 'HYGYENE', 160, 2.80, 0, 'Limpia y reduce bacterias'),
    ('Shampoo anticaspa', 'Shampoo caspa', 'HYGYENE', 70, 8.90, 0, 'Controla la caspa del cuero cabelludo'),
    ('Acondicionador reparador', 'Acondicionador', 'HYGYENE', 65, 7.40, 0, 'Suaviza el cabello maltratado'),
    ('Crema dental menta', 'Crema dental', 'HYGYENE', 180, 3.10, 0, 'Protege dientes y refresca el aliento'),
    ('Cepillo dental adulto', 'Cepillo dental', 'HYGYENE', 140, 2.40, 0, 'Limpieza diaria de dientes'),
    ('Enjuague bucal', 'Enjuague bucal', 'HYGYENE', 90, 5.60, 0, 'Reduce placa y refresca la boca'),
    ('Hilo dental', 'Hilo dental', 'HYGYENE', 110, 2.70, 0, 'Retira restos entre los dientes'),
    ('Desodorante roll-on', 'Desodorante', 'HYGYENE', 100, 4.50, 0, 'Controla el olor corporal'),
    ('Talco corporal', 'Talco', 'HYGYENE', 80, 3.30, 0, 'Absorbe humedad y da frescura'),
    ('Papel higienico 4 rollos', 'Papel higienico', 'HYGYENE', 200, 3.90, 0, 'Higiene diaria del hogar'),
    ('Toallas humedas', 'Toallas humedas', 'HYGYENE', 130, 2.60, 0, 'Limpieza suave de la piel'),
    ('Panales talla M', 'Panales M', 'HYGYENE', 90, 12.80, 0, 'Pañal absorbente para bebes'),
    ('Panales talla G', 'Panales G', 'HYGYENE', 85, 13.40, 0, 'Pañal para bebes mas grandes'),
    ('Toallas sanitarias', 'Toallas sanitarias', 'HYGYENE', 120, 4.20, 0, 'Proteccion menstrual diaria'),
    ('Protectores diarios', 'Protectores', 'HYGYENE', 110, 3.60, 0, 'Proteccion ligera para el dia'),
    ('Jabon intimo', 'Jabon intimo', 'HYGYENE', 60, 6.10, 0, 'Limpieza suave de la zona intima'),
    ('Gel antibacterial', 'Gel antibacterial', 'HYGYENE', 150, 3.20, 0, 'Desinfecta las manos sin agua'),
    ('Alcohol 70 por ciento', 'Alcohol 70', 'HYGYENE', 100, 2.90, 0, 'Desinfectante de superficies'),
    ('Hisopos', 'Hisopos', 'HYGYENE', 140, 1.70, 0, 'Higiene de oidos y maquillaje'),
    ('Algodon hidrofilo', 'Algodon', 'HYGYENE', 90, 2.30, 0, 'Uso en curaciones y aseo'),
    ('Cortauñas', 'Cortauñas', 'HYGYENE', 50, 1.90, 0, 'Cuidado de unas de manos y pies'),
    ('Rasuradoras desechables', 'Rasuradoras', 'HYGYENE', 120, 3.40, 0, 'Afeitado practico de un uso'),
    ('Espuma de afeitar', 'Espuma afeitar', 'HYGYENE', 55, 5.80, 0, 'Suaviza la piel al afeitar'),
    ('Shampoo bebe', 'Shampoo bebe', 'HYGYENE', 70, 6.70, 0, 'Limpieza suave para el bebe'),
    ('Jabon bebe', 'Jabon bebe', 'HYGYENE', 80, 3.80, 0, 'Jabon hipoalergenico infantil'),
    ('Aceite bebe', 'Aceite bebe', 'HYGYENE', 60, 5.40, 0, 'Hidrata la piel delicada'),
    ('Crema antipanalitis', 'Antipanalitis', 'HYGYENE', 75, 6.20, 0, 'Previene la rozadura del panal'),
    ('Jabon de glicerina', 'Jabon glicerina', 'HYGYENE', 90, 2.50, 0, 'Limpia sin resecar la piel'),
    ('Shampoo neutro', 'Shampoo neutro', 'HYGYENE', 65, 6.90, 0, 'Limpieza diaria del cabello'),
    ('Mascarilla capilar', 'Mascarilla', 'HYGYENE', 40, 8.30, 0, 'Nutre y repara el cabello'),
    ('Gel de ducha', 'Gel ducha', 'HYGYENE', 85, 5.10, 0, 'Limpieza corporal con espuma'),
    ('Esponja de bano', 'Esponja', 'HYGYENE', 70, 1.60, 0, 'Ayuda a exfoliar en la ducha'),
    ('Cepillo de cabello', 'Cepillo cabello', 'HYGYENE', 45, 4.80, 0, 'Desenreda sin maltratar'),
    ('Peinilla', 'Peinilla', 'HYGYENE', 55, 2.10, 0, 'Peinado diario del cabello'),
    ('Ligas para el cabello', 'Ligas cabello', 'HYGYENE', 100, 1.40, 0, 'Sujeta el cabello con suavidad'),
    ('Desodorante en barra', 'Desodorante barra', 'HYGYENE', 95, 4.10, 0, 'Proteccion contra el sudor'),
    ('Desodorante en spray', 'Desodorante spray', 'HYGYENE', 80, 5.20, 0, 'Frescura de larga duracion'),
    ('Pañitos desinfectantes', 'Pañitos', 'HYGYENE', 110, 3.70, 0, 'Limpia superficies de uso diario'),
    ('Jabon liquido para manos', 'Jabon manos', 'HYGYENE', 130, 3.50, 0, 'Lavado frecuente de manos'),
    ('Crema dental blanqueadora', 'Dental blanc', 'HYGYENE', 90, 4.60, 0, 'Ayuda a aclarar los dientes'),
    ('Cepillo dental infantil', 'Cepillo infantil', 'HYGYENE', 75, 2.80, 0, 'Cepillo suave para ninos'),
    ('Enjuague bucal sin alcohol', 'Enjuague suave', 'HYGYENE', 60, 5.90, 0, 'Enjuague suave para encias'),
    ('Seda dental menta', 'Seda dental', 'HYGYENE', 85, 2.40, 0, 'Hilo dental con sabor a menta'),
    ('Protector de cama', 'Protector cama', 'HYGYENE', 40, 9.80, 0, 'Protege el colchon de humedad'),
    ('Tampones', 'Tampones', 'HYGYENE', 70, 4.90, 0, 'Proteccion interna menstrual'),
    ('Jabon de azufre', 'Jabon azufre', 'HYGYENE', 35, 3.90, 0, 'Ayuda a limpiar piel grasa'),
    ('Shampoo de ketoconazol', 'Shampoo keto', 'HYGYENE', 45, 9.60, 0, 'Shampoo para caspa persistente'),
    ('Crema hidratante corporal', 'Crema corporal', 'PERSONAL_CARE', 90, 8.40, 0, 'Hidrata la piel seca'),
    ('Bloqueador solar FPS 50', 'Bloqueador 50', 'PERSONAL_CARE', 70, 14.90, 0, 'Protege del sol de alta exposicion'),
    ('Bloqueador solar FPS 30', 'Bloqueador 30', 'PERSONAL_CARE', 65, 11.50, 0, 'Proteccion solar de uso diario'),
    ('Crema para manos', 'Crema manos', 'PERSONAL_CARE', 100, 4.70, 0, 'Hidrata manos resecas'),
    ('Balsamo labial', 'Balsamo labial', 'PERSONAL_CARE', 120, 2.90, 0, 'Humecta labios secos'),
    ('Crema contorno de ojos', 'Contorno ojos', 'PERSONAL_CARE', 40, 16.80, 0, 'Cuida la piel alrededor del ojo'),
    ('Serum vitamina C', 'Serum vit C', 'PERSONAL_CARE', 35, 18.40, 0, 'Ilumina y unifica el tono'),
    ('Agua micelar', 'Agua micelar', 'PERSONAL_CARE', 80, 9.20, 0, 'Limpia el rostro sin enjuagar'),
    ('Desmaquillante bifasico', 'Desmaquillante', 'PERSONAL_CARE', 50, 8.70, 0, 'Retira maquillaje a prueba de agua'),
    ('Tonico facial', 'Tonico facial', 'PERSONAL_CARE', 45, 10.30, 0, 'Equilibra la piel despues de limpiar'),
    ('Crema antiarrugas', 'Antiarrugas', 'PERSONAL_CARE', 30, 19.90, 0, 'Atenua lineas de expresion'),
    ('Locion after shave', 'After shave', 'PERSONAL_CARE', 40, 7.60, 0, 'Calma la piel tras el afeitado'),
    ('Colonia fresca', 'Colonia', 'PERSONAL_CARE', 55, 12.40, 0, 'Fragancia ligera para el dia'),
    ('Perfume floral', 'Perfume', 'PERSONAL_CARE', 25, 24.50, 0, 'Fragancia de larga duracion'),
    ('Crema para pies', 'Crema pies', 'PERSONAL_CARE', 60, 6.30, 0, 'Suaviza talones resecos'),
    ('Talco para pies', 'Talco pies', 'PERSONAL_CARE', 70, 3.80, 0, 'Mantiene los pies secos'),
    ('Aceite de almendras', 'Aceite almendras', 'PERSONAL_CARE', 40, 7.90, 0, 'Nutre piel y cabello'),
    ('Crema de rosa mosqueta', 'Rosa mosqueta', 'PERSONAL_CARE', 35, 11.20, 0, 'Regenera y suaviza la piel'),
    ('Protector labial FPS', 'Labial FPS', 'PERSONAL_CARE', 90, 3.40, 0, 'Protege los labios del sol'),
    ('Gel fijador', 'Gel fijador', 'PERSONAL_CARE', 55, 5.70, 0, 'Fija el peinado sin residuos'),
    ('Cera para cabello', 'Cera cabello', 'PERSONAL_CARE', 45, 6.40, 0, 'Da textura y control al pelo'),
    ('Spray fijador', 'Spray fijador', 'PERSONAL_CARE', 40, 6.80, 0, 'Mantiene el peinado en su lugar'),
    ('Tinte capilar negro', 'Tinte negro', 'PERSONAL_CARE', 30, 8.90, 0, 'Color negro de cobertura completa'),
    ('Tinte capilar castaño', 'Tinte castaño', 'PERSONAL_CARE', 30, 8.90, 0, 'Color castaño de uso en casa'),
    ('Decolorante capilar', 'Decolorante', 'PERSONAL_CARE', 20, 7.50, 0, 'Aclara el color del cabello'),
    ('Crema depilatoria', 'Crema depilatoria', 'PERSONAL_CARE', 50, 6.60, 0, 'Retira el vello sin rasurar'),
    ('Bandas depilatorias', 'Bandas depil', 'PERSONAL_CARE', 45, 5.20, 0, 'Depilacion rapida en casa'),
    ('Crema corporal de cocoa', 'Crema cocoa', 'PERSONAL_CARE', 60, 9.10, 0, 'Hidratacion con aroma a cocoa'),
    ('Locion corporal', 'Locion corporal', 'PERSONAL_CARE', 75, 7.30, 0, 'Humecta despues del bano'),
    ('Exfoliante facial', 'Exfoliante', 'PERSONAL_CARE', 40, 8.80, 0, 'Renueva la piel del rostro'),
    ('Mascarilla de arcilla', 'Mascarilla arcilla', 'PERSONAL_CARE', 35, 7.70, 0, 'Limpia poros y controla grasa'),
    ('Mascarilla hidratante', 'Mascarilla hidra', 'PERSONAL_CARE', 40, 8.20, 0, 'Aporta agua a la piel seca'),
    ('Aceite de coco', 'Aceite coco', 'PERSONAL_CARE', 55, 6.90, 0, 'Nutre piel, labios y cabello'),
    ('Crema de noche', 'Crema noche', 'PERSONAL_CARE', 30, 15.60, 0, 'Repara la piel mientras duermes'),
    ('Crema de dia', 'Crema dia', 'PERSONAL_CARE', 35, 14.20, 0, 'Hidrata y protege durante el dia'),
    ('Base de maquillaje', 'Base maquillaje', 'PERSONAL_CARE', 25, 13.80, 0, 'Unifica el tono del rostro'),
    ('Polvo compacto', 'Polvo compacto', 'PERSONAL_CARE', 25, 11.40, 0, 'Fija el maquillaje y matifica'),
    ('Labial', 'Labial', 'PERSONAL_CARE', 80, 4.30, 0, 'Color y humectacion para labios'),
    ('Rimel', 'Rimel', 'PERSONAL_CARE', 40, 7.10, 0, 'Alarga y define las pestanas'),
    ('Delineador de ojos', 'Delineador', 'PERSONAL_CARE', 35, 5.90, 0, 'Define el contorno del ojo'),
    ('Sombras para ojos', 'Sombras', 'PERSONAL_CARE', 30, 9.40, 0, 'Color para el maquillaje de ojos'),
    ('Esmalte de uñas', 'Esmalte', 'PERSONAL_CARE', 90, 2.80, 0, 'Color para unas de manos y pies'),
    ('Quitaesmalte', 'Quitaesmalte', 'PERSONAL_CARE', 60, 3.20, 0, 'Retira el esmalte de las unas'),
    ('Crema de cuticulas', 'Crema cuticulas', 'PERSONAL_CARE', 40, 4.50, 0, 'Suaviza cuticulas resecas'),
    ('Lima de uñas', 'Lima uñas', 'PERSONAL_CARE', 100, 1.50, 0, 'Da forma a las unas'),
    ('Crema para estrias', 'Crema estrias', 'PERSONAL_CARE', 25, 12.70, 0, 'Mejora la apariencia de estrias'),
    ('Aceite para masaje', 'Aceite masaje', 'PERSONAL_CARE', 30, 8.60, 0, 'Facilita el masaje corporal'),
    ('Sales de baño', 'Sales baño', 'PERSONAL_CARE', 45, 5.40, 0, 'Relaja en un bano tibio'),
    ('Crema corporal de avena', 'Crema avena', 'PERSONAL_CARE', 55, 7.80, 0, 'Calma y humecta piel sensible'),
    ('Protector solar infantil', 'Solar infantil', 'PERSONAL_CARE', 40, 13.20, 0, 'Proteccion solar suave para ninos'),
    ('Vitamina D3 1000 UI', 'Vitamina D3', 'MEDICINES', 80, 6.40, 0, 'Apoya huesos y defensas'),
    ('Crema corporal de karite', 'Crema karite', 'PERSONAL_CARE', 50, 9.70, 0, 'Hidrata con manteca de karite');
